---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"

- name: restart firewalld
  systemd:
    name: "{{ firewalld_service_name }}"
    state: "{{ firewalld_service_state }}"
