---
     - name: Install the package
       yum:
        name: /tmp/NessusAgent-es7.x86_64.rpm
        state: present

    - name: Start nessusagent, if not started
      service:
        name: nessusagent
        state: started

    - name: To remove the nessus rpm file from /tmp
      file:
        path: /tmp/NessusAgent-es7.x86_64.rpm
        state: absent
